### ISSUE TITLE
`kube.Export` using `kube.WithExportStdOut()` cannot be piped to `kubectl` without `kube.WithExportAsSingleFile("xyz")`

### ISSUE THREAD

**Issue by jlarfors** [volvo-cars/lingon#119]
Using `kube.Export(...)` with `kube.WithExportStdOut()` results in the output having something like:

```yaml
-- out/4_account.yaml --
apiVersion: ...
kind: ...
...
```

The 1st line makes this invalid YAML, according to `kubectl`. Hacky fix was to use `kube.WithExportAsSingleFile("a")`. Amazingly providing an empty string `""` did not work so I gave a string value like `"a"` and it does. Now I get:

```yaml
---
# out/4_account.yaml
apiVersion: ...
kind: ...
...
```

I assume this is coming from txtar and by default I'd think stdout exports should be pipe-able to `kubectl`.
