### ISSUE TITLE
Neat output from `kube.Export()`

### ISSUE THREAD

**Issue by LeonardAukea** [volvo-cars/lingon#70]
I noticed that there were some redundant fields present in the output from `kube.Export()` eg. 

```yaml 
creationTimestamp: null
...
status:
   ...
```

The plugin `kubectl-neat` has some code to removes redundant fields, have a look here https://github.com/itaysk/kubectl-neat/blob/master/cmd/neat_test.go
